In [1]:
# Dependencies
from selenium import webdriver
import time
from price import page_data

In [2]:
# set up browser
url = "https://www.homedepot.com/b/Appliances/N-5yc1vZbv1w"

browser = webdriver.Chrome()

In [3]:
# go to url and navigate to first set of refrigerators
browser.get(url)

#select refrigerators from the appliance section
appliances = browser.find_elements_by_class_name("visualNav__title-center")

appliances[0].click()

#select french door refrigerators
time.sleep(0.08)
fridge = browser.find_elements_by_class_name("etchVisualNavigationStory__card__title")
fridge[0].click()

In [4]:
time.sleep(0.05)
html = browser.page_source

In [5]:
first_pg = page_data(html)

In [7]:
first_pg

,price,brand,sku,worst_rating,best_rating,review_count,avg_ratings
6,"$3,418.00",GE,311411352,1,5,1084,4.6559
18,"$1,978.00",GE,312980601,1,5,3061,4.4397
22,"$2,728.00",GE,312648552,1,5,3977,4.4068
13,"$1,708.00",GE,303345832,1,5,2048,4.2139
0,"$1,998.00",LG Electronics,302253240,1,5,1162,4.2633
20,"$1,708.00",LG Electronics,306803830,1,5,504,4.3929
3,"$1,098.00",LG Electronics,206452443,1,5,2500,4.4324
4,"$1,618.00",LG Electronics,205033976,1,5,656,4.3796
5,"$1,098.00",LG Electronics,206452443,1,5,2500,4.4324
17,"$2,739.00",LG Electronics,305712398,1,5,964,4.4886
10,"$1,198.00",LG Electronics,314145556,1,5,40,4.15
12,"$2,289.00",LG Electronics,306750351,1,5,1426,4.3808
14,"$2,199.00",LG Electronics,305573330,1,5,1825,4.4126
16,"$3,999.00",LG Electronics,312285857,1,5,159,4.2013
21,"$1,498.00",Samsung,203707196,1,5,1486,4.3264
19,"$2,878.00",Samsung,312904454,1,5,467,4.6017
11,"$1,248.00",Samsung,302577277,1,5,1793,3.8232
9,"$1,708.00",Samsung,314024432,1,5,83,4.2771
8,"$2,698.00",Samsung,308743988,1,5,1258,4.2591
2,"$2,158.00",Samsung,312904394,1,5,386,4.2953
15,"$2,518.00",Samsung,310428856,1,5,917,4.2257
23,"$3,418.00",Samsung,310516279,1,5,1464,4.6865
7,"$2,199.00",Whirlpool,301711642,1,5,4155,4.4022
1,"$2,499.00",Whirlpool,301859152,1,5,5977,4.4877